version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/koron/imghead
    steps:
      - run:
          name: Golang version
          command: |
            go version
            go env
      - checkout

      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test all
          command: go test -v ./...
      - run:
          name: Build
          command: go build -v

      - run:
          name: Correct artifacts
          command: |
            mkdir /tmp/artifacts
            cp imghead /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
